[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "propertycrawler"
version = "0.1"

[project.scripts]
propertycrawler = "propertycrawler:main"

[tool.hatch.build.targets.wheel]
packages = ["src/propertycrawler"]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src/", "src/propertycrawler",
]